version: '3'

services:
  web:
    build: .
    network_mode: host
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
    - "8000:8000"
    command: gunicorn TeamBackend.wsgi:application --bind 0.0.0.0:8000
      

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: teamprojuser
      POSTGRES_PASSWORD: teamprojuser
      POSTGRES_DB: teamprojdb

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
      - db
    volumes:
      - ./TeamBackend/static:/app/static
      - ./frontend/build:/app/react_app/build
      - /etc/letsencrypt/archive/matchpoint.games:/etc/nginx/ssl/matchpoint.games
